#!/usr/bin/env python3
"""
Gamma-AIF simulation/inference agreement script for HP-13C pyruvate/lactate kinetics.

This version keeps the simulation and NLLS comparison consistent with the
protocol-specific gamma-variate vascular-input model used for the primary
manuscript comparison:

1) Clean pyruvate/lactate curves are generated by the project two-compartment
   generator.
2) Independent zero-mean Gaussian noise is added to pyruvate and lactate using
   the same rms amplitude, sigma, within each sample.
3) NLLS uses fit_nlls_gamma_AIF(), which jointly estimates kPL, kVE, vB and the
   gamma-variate vascular-input parameters from the noisy pyruvate/lactate curves.
4) NLLS displayed curves are taken from the fitted gamma-AIF forward model. NN
   displayed curves are generated by fitting only the gamma-AIF nuisance
   parameters with the NN kinetic estimates held fixed.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from datetime import datetime
from typing import Dict, Iterable, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
import torch

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from fit_two_compartment_physio_nlls import (
    fit_nlls_gamma_AIF,
    gamma_variate_input,
    simulate_physio_from_Pv,
)
from hybrid_model_utils import (
    HybridMultiHead,
    compute_peak_percentile,
    load_training_config,
    plot_prediction_scatter,
    prepare_hybrid_inputs,
)


PARAMETER_NAMES = ("kPL", "kVE", "vB")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run simulated HP-13C data inference with equal-rms noise for pyruvate and lactate."
    )
    parser.add_argument(
        "--weights-dir",
        required=True,
        help="Subdirectory under output/ containing trained_hybrid_positive.pth and training_report.md.",
    )
    parser.add_argument(
        "--output-dir",
        default="output",
        help="Root output directory containing weights-dir. Default: output.",
    )
    parser.add_argument(
        "--n-samples",
        type=int,
        default=50,
        help="Number of simulated curves for agreement plots. Default: 50.",
    )
    parser.add_argument(
        "--noise-seed",
        type=int,
        default=20260516,
        help="Random seed for the added equal-rms Gaussian noise. Default: 20260516.",
    )
    parser.add_argument(
        "--snr-min",
        type=float,
        default=None,
        help="Override lower bound for target pyruvate SNR. Default: training_report SNR_MIN.",
    )
    parser.add_argument(
        "--snr-max",
        type=float,
        default=None,
        help="Override upper bound for target pyruvate SNR. Default: training_report SNR_MAX.",
    )
    parser.add_argument(
        "--fixed-pyr-snr",
        type=float,
        default=None,
        help=(
            "Use one fixed target pyruvate SNR for all samples instead of drawing from an SNR range. "
            "This is useful when regenerating a specific Figure 3/S1B/S2B panel."
        ),
    )
    parser.add_argument(
        "--n-examples",
        type=int,
        default=3,
        help="Number of low/medium/high-kPL time-course examples to plot. Default: 3.",
    )
    parser.add_argument(
        "--bootstrap",
        type=int,
        default=200,
        help="Bootstrap iterations for R^2 uncertainty. Default: 200.",
    )
    parser.add_argument(
        "--use-weighted-nlls",
        action="store_true",
        help="Pass the known same sigma to NLLS as sigma_pyr=sigma_lac=sigma for each sample.",
    )
    parser.add_argument(
        "--clip-negative-noisy-signal",
        action="store_true",
        help="Clip noisy simulated signals at zero. Default is not to clip because Gaussian noise is zero-mean.",
    )
    # Ignore unrelated args from debuggers/notebooks while still enforcing required args.
    args, _ = parser.parse_known_args()
    return args


def _as_schedule(x: Sequence[float] | float, n: int) -> np.ndarray:
    arr = np.asarray(x, dtype=float)
    if arr.ndim == 0:
        return np.repeat(float(arr), n)
    if arr.size == n:
        return arr.astype(float)
    if arr.size > n:
        return arr[:n].astype(float)
    return np.pad(arr.astype(float), (0, n - arr.size), mode="edge")


def r1_app_schedule(R1: float, flip_angle_deg: Sequence[float] | float, TR: float, n: int) -> np.ndarray:
    """Return R1,app(t) = R1 - log(cos(theta(t))) / TR for each acquired time point."""
    fa = _as_schedule(flip_angle_deg, n)
    c = np.cos(np.deg2rad(fa))
    c = np.clip(c, 1e-8, 1.0)
    return float(R1) - np.log(c) / float(TR)



def build_generator(cfg: Dict[str, float], time_points: np.ndarray):
    aif_key = str(cfg["AIF_TYPE"]).strip().lower().replace("-", "_").replace(" ", "_")
    kwargs = dict(
        vb_range=(cfg["VB_MIN"], cfg["VB_MAX"]),
        kpl_range=(cfg["KPL_MIN"], cfg["KPL_MAX"]),
        kve_range=(cfg["KVE_MIN"], cfg["KVE_MAX"]),
        r1p_range=(1/60, 1/20),
        r1l_range=(1/55, 1/15),
        time_points=time_points,
        flip_angle_pyr_deg=cfg["PYR_FA_SCHEDULE"],
        flip_angle_lac_deg=cfg["LAC_FA_SCHEDULE"],
        TR=cfg["SCAN_TR"],
    )
    if aif_key in ["measured", "physio", "physiologic", "physiological"]:
        from two_compartment_generator_physio import TwoCompartmentHPDataGeneratorPhysio
        return TwoCompartmentHPDataGeneratorPhysio(**kwargs), aif_key
    raise ValueError(f"Unrecognized AIF_TYPE: {cfg['AIF_TYPE']}")


def generate_clean_dataset(generator, n_samples: int) -> Tuple[np.ndarray, np.ndarray, object, object]:
    """
    Generate clean simulated curves directly from the project generator.

    Prefer generator-side noise_std=0.0 when available. The equal-rms noise used
    for reporting is added later by add_equal_rms_noise().
    """
    try:
        return generator.generate_dataset(n_samples=n_samples, noise_std=0.0)
    except TypeError:
        try:
            return generator.generate_dataset(n_samples=n_samples, snr_range=(1e12, 1e12))
        except TypeError:
            return generator.generate_dataset(n_samples=n_samples)


def add_equal_rms_noise(
    X_clean: np.ndarray,
    rng: np.random.Generator,
    target_pyr_snr_range: Tuple[float, float],
    fixed_pyr_snr: Optional[float] = None,
    clip_negative: bool = False,
) -> Tuple[np.ndarray, pd.DataFrame]:
    """
    Add independent zero-mean Gaussian noise with identical rms amplitude in both channels.

    Returns
    -------
    X_noisy : ndarray, shape (N,T,2)
        Noisy pyruvate/lactate curves.
    noise_df : DataFrame
        Per-sample sigma and SNR information. sigma is the same denominator used for
        pyruvate and lactate within that sample.
    """
    X_clean = np.asarray(X_clean, dtype=float)
    if X_clean.ndim != 3 or X_clean.shape[-1] != 2:
        raise ValueError("X_clean must have shape (n_samples, n_timepoints, 2).")

    peak_pyr = np.nanmax(np.abs(X_clean[:, :, 0]), axis=1)
    peak_lac = np.nanmax(np.abs(X_clean[:, :, 1]), axis=1)
    peak_pyr = np.maximum(peak_pyr, 1e-12)

    n = X_clean.shape[0]
    if fixed_pyr_snr is not None:
        target_pyr_snr = np.full(n, float(fixed_pyr_snr), dtype=float)
    else:
        lo, hi = map(float, target_pyr_snr_range)
        if lo <= 0 or hi <= 0 or hi < lo:
            raise ValueError(f"Invalid target pyruvate SNR range: {target_pyr_snr_range}")
        target_pyr_snr = rng.uniform(lo, hi, size=n)

    # Same rms noise amplitude for both metabolites in the same voxel/sample.
    sigma = peak_pyr / np.maximum(target_pyr_snr, 1e-12)
    noise = rng.normal(loc=0.0, scale=sigma[:, None, None], size=X_clean.shape)
    X_noisy = X_clean + noise
    if clip_negative:
        X_noisy = np.maximum(X_noisy, 0.0)

    snr_pyr = peak_pyr / sigma
    snr_lac = peak_lac / sigma
    noise_df = pd.DataFrame(
        {
            "sample": np.arange(n, dtype=int),
            "sigma_equal_rms": sigma,
            "clean_peak_pyr": peak_pyr,
            "clean_peak_lac": peak_lac,
            "snr_pyr": snr_pyr,
            "snr_lac": snr_lac,
            "target_snr_pyr": target_pyr_snr,
        }
    )
    return X_noisy, noise_df


def prepare_inputs_for_model(X: np.ndarray, cfg: Dict[str, float], P_train: float):
    P_clin = compute_peak_percentile(
        X,
        percentile=cfg["PERCENTILE"],
        pyr_channel=0,
        min_peak=1e-6,
    )
    alpha = P_train / max(P_clin, 1e-8)
    X_norm, X_raw, clin_meta = prepare_hybrid_inputs(
        X,
        alpha=alpha,
        pyr_channel=0,
        flatten=True,
    )
    Xr = X_raw.reshape(X.shape[0], -1)
    Xn = X_norm.reshape(X.shape[0], -1)
    return Xn, Xr, X_norm, X_raw, clin_meta, alpha, P_clin


def finite_r2(y_true: np.ndarray, y_pred: np.ndarray) -> np.ndarray:
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    out = np.full(y_true.shape[1], np.nan, dtype=float)
    for p_idx in range(y_true.shape[1]):
        mask = np.isfinite(y_true[:, p_idx]) & np.isfinite(y_pred[:, p_idx])
        if np.count_nonzero(mask) < 2:
            continue
        den = np.sum((y_true[mask, p_idx] - np.mean(y_true[mask, p_idx])) ** 2)
        if den <= 0:
            continue
        num = np.sum((y_pred[mask, p_idx] - y_true[mask, p_idx]) ** 2)
        out[p_idx] = 1.0 - num / den
    return out


def bootstrap_r2_std(y_true: np.ndarray, y_pred: np.ndarray, B: int, rng: np.random.Generator) -> np.ndarray:
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    n, p = y_true.shape
    vals = np.full((B, p), np.nan, dtype=float)
    if n < 2 or B <= 1:
        return np.full(p, np.nan, dtype=float)
    for b in range(B):
        idx = rng.integers(0, n, size=n)
        vals[b, :] = finite_r2(y_true[idx], y_pred[idx])
    return np.nanstd(vals, axis=0, ddof=1)


def save_true_vs_pred_csv_and_quickplot(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    run_dir: str,
    basename: str,
) -> str:
    df = pd.DataFrame(
        {
            "kPL_true": y_true[:, 0],
            "kVE_true": y_true[:, 1],
            "vB_true": y_true[:, 2],
            "kPL_pred": y_pred[:, 0],
            "kVE_pred": y_pred[:, 1],
            "vB_pred": y_pred[:, 2],
        }
    )
    csv_path = os.path.join(run_dir, f"{basename}.csv")
    df.to_csv(csv_path, index=False)

    fig, axes = plt.subplots(1, 3, figsize=(15, 4), constrained_layout=True)
    for i, label in enumerate(PARAMETER_NAMES):
        ax = axes[i]
        ax.scatter(y_true[:, i], y_pred[:, i], alpha=0.6)
        lo = np.nanmin([np.nanmin(y_true[:, i]), np.nanmin(y_pred[:, i])])
        hi = np.nanmax([np.nanmax(y_true[:, i]), np.nanmax(y_pred[:, i])])
        pad = 0.05 * (hi - lo + 1e-12)
        lims = (lo - pad, hi + pad)
        ax.plot(lims, lims, "r--", lw=1.25)
        ax.set_xlim(lims)
        ax.set_ylim(lims)
        r2 = finite_r2(y_true[:, [i]], y_pred[:, [i]])[0]
        ax.set_xlabel("True")
        ax.set_ylabel("Predicted")
        ax.set_title(f"{label}: R$^2$={r2:.3f}")
    fig.savefig(os.path.join(run_dir, f"true_vs_pred_{basename}.png"), dpi=300)
    plt.close(fig)
    return csv_path


def run_nlls_fits(
    X: np.ndarray,
    y_true: np.ndarray,
    noise_df: pd.DataFrame,
    cfg: Dict[str, float],
    time_points: np.ndarray,
    weighted: bool,
    aif_key: str,
) -> Tuple[np.ndarray, list, int, float]:
    """Run the primary gamma-variate AIF NLLS comparator for every sample."""
    nlls_bounds = (
        (cfg["KPL_MIN"], cfg["KVE_MIN"], cfg["VB_MIN"]),
        (cfg["KPL_MAX"], cfg["KVE_MAX"], cfg["VB_MAX"]),
    )
    nlls_p0 = (
        0.5 * (cfg["KPL_MIN"] + cfg["KPL_MAX"]),
        0.5 * (cfg["KVE_MIN"] + cfg["KVE_MAX"]),
        0.5 * (cfg["VB_MIN"] + cfg["VB_MAX"]),
    )

    nlls_preds = []
    nlls_results = []
    nlls_failures = 0
    start = time.time()
    for j in range(X.shape[0]):
        pyr = X[j, :, 0]
        lac = X[j, :, 1]
        sigma_j = float(noise_df.loc[j, "sigma_equal_rms"])
        try:
            res = fit_nlls_gamma_AIF(
                time_points=time_points,
                S_pyr_obs=pyr,
                S_lac_obs=lac,
                TR=cfg["SCAN_TR"],
                flips_pyr_deg=cfg["PYR_FA_SCHEDULE"],
                flips_lac_deg=cfg["LAC_FA_SCHEDULE"],
                R1p=1 / 30,
                R1l=1 / 25,
                p0=nlls_p0,
                bounds=nlls_bounds,
                sigma_pyr=sigma_j if weighted else None,
                sigma_lac=sigma_j if weighted else None,
                seed=12345 + j,
            )
            nlls_results.append(res)
            if bool(res.get("success", False)):
                nlls_preds.append([res["kpl"], res["kve"], res["vb"]])
            else:
                nlls_preds.append([np.nan, np.nan, np.nan])
                nlls_failures += 1
        except Exception as exc:
            nlls_results.append({"success": False, "message": repr(exc)})
            nlls_preds.append([np.nan, np.nan, np.nan])
            nlls_failures += 1
    elapsed = time.time() - start
    return np.asarray(nlls_preds, dtype=float), nlls_results, nlls_failures, elapsed


def _result_curve_from_keys(res: dict, possible_keys: Iterable[str]) -> Optional[np.ndarray]:
    if not isinstance(res, dict):
        return None
    for key in possible_keys:
        if key in res and res[key] is not None:
            arr = np.asarray(res[key], dtype=float)
            if arr.ndim == 1:
                return arr
    return None


def fit_gamma_aif_given_fixed_kinetics(
    time_points: np.ndarray,
    S_pyr_obs: np.ndarray,
    S_lac_obs: np.ndarray,
    TR: float,
    flips_pyr_deg: Sequence[float] | float,
    flips_lac_deg: Sequence[float] | float,
    kpl: float,
    kve: float,
    vb: float,
    R1p: float = 1 / 30,
    R1l: float = 1 / 25,
    sigma_pyr: Optional[float] = None,
    sigma_lac: Optional[float] = None,
    n_starts: int = 5,
    seed: int = 12345,
) -> dict:
    """
    Fit only the gamma-variate AIF nuisance parameters with kPL/kVE/vB fixed.

    This is used only to display an NN-implied forward curve. It does not change
    the NN parameter estimates and is not used for quantitative NN inference.
    """
    from scipy.optimize import least_squares

    t = np.asarray(time_points, dtype=float).reshape(-1)
    pyr = np.asarray(S_pyr_obs, dtype=float).reshape(-1)
    lac = np.asarray(S_lac_obs, dtype=float).reshape(-1)
    n = t.size

    R1app_P = r1_app_schedule(R1p, flips_pyr_deg, TR, n)
    R1app_L = r1_app_schedule(R1l, flips_lac_deg, TR, n)

    peak_obs = max(float(np.nanmax(pyr)), 1e-6)
    t_peak = float(t[int(np.nanargmax(pyr))])

    lb = np.array([0.05 * peak_obs, 1.0, 0.05, t[0] - 2 * float(TR)], dtype=float)
    ub = np.array([20.0 * peak_obs, 6.0, 2.0, min(float(t[-1]), t_peak)], dtype=float)
    p0 = np.array([peak_obs, 3.0, 0.8, max(float(t[0]) - float(TR), t_peak - 4.0)], dtype=float)
    eps = 1e-10 * (ub - lb + 1.0)
    p0 = np.minimum(np.maximum(p0, lb + eps), ub - eps)

    if sigma_pyr is None:
        sigma_pyr = max(float(np.nanmax(np.abs(pyr))), 1e-6)
    if sigma_lac is None:
        sigma_lac = max(float(np.nanmax(np.abs(lac))), 1e-6)

    def residual(aif_theta: np.ndarray) -> np.ndarray:
        peak_amp, alpha, beta, t0 = map(float, aif_theta)
        Pv = gamma_variate_input(t, peak_amp, alpha, beta, t0)
        S_pyr_fit, S_lac_fit, Pe_fit, L_fit = simulate_physio_from_Pv(
            t, Pv, kpl, kve, vb, R1app_P, R1app_L
        )
        r_p = (S_pyr_fit - pyr) / float(sigma_pyr)
        r_l = (S_lac_fit - lac) / float(sigma_lac)
        r = np.concatenate([r_p, r_l])
        r[~np.isfinite(r)] = 1e6
        return r

    rng = np.random.default_rng(seed)
    starts = [p0]
    for _ in range(max(0, int(n_starts) - 1)):
        x = lb + rng.random(lb.size) * (ub - lb)
        x[0] = rng.uniform(0.5 * peak_obs, 3.0 * peak_obs)
        x[1] = rng.uniform(2.0, 4.5)
        x[2] = rng.uniform(0.2, 1.2)
        x[3] = rng.uniform(lb[3], ub[3])
        starts.append(np.minimum(np.maximum(x, lb + eps), ub - eps))

    best = None
    for start in starts:
        res = least_squares(
            residual,
            start,
            bounds=(lb, ub),
            method="trf",
            max_nfev=40000,
            x_scale="jac",
        )
        if best is None or res.cost < best.cost:
            best = res

    peak_amp, alpha, beta, t0 = map(float, best.x)
    Pv_fit = gamma_variate_input(t, peak_amp, alpha, beta, t0)
    S_pyr_fit, S_lac_fit, Pe_fit, L_fit = simulate_physio_from_Pv(
        t, Pv_fit, kpl, kve, vb, R1app_P, R1app_L
    )
    return {
        "success": bool(best.success),
        "cost": float(best.cost),
        "AIF_peak_amp": peak_amp,
        "AIF_alpha": alpha,
        "AIF_beta": beta,
        "AIF_t0": t0,
        "Pv_fit": Pv_fit,
        "Pe_fit": Pe_fit,
        "L_fit": L_fit,
        "S_pyr_fit": S_pyr_fit,
        "S_lac_fit": S_lac_fit,
    }


def fitted_curves_for_plot(
    aif_key: str,
    generator,
    time_points: np.ndarray,
    pyr_obs: np.ndarray,
    lac_obs: np.ndarray,
    params: Sequence[float],
    cfg: Dict[str, float],
    nlls_res: Optional[dict] = None,
    sigma_pyr: Optional[float] = None,
    sigma_lac: Optional[float] = None,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return pyruvate/lactate curves from the gamma-AIF forward model."""
    # For NLLS, use the fitted curves returned by fit_nlls_gamma_AIF().
    if isinstance(nlls_res, dict):
        pyr_fit = _result_curve_from_keys(nlls_res, ["S_pyr_fit", "pyr_fit", "S_pyr_pred"])
        lac_fit = _result_curve_from_keys(nlls_res, ["S_lac_fit", "lac_fit", "S_lac_pred"])
        if pyr_fit is not None and lac_fit is not None:
            return pyr_fit, lac_fit

    try:
        kpl, kve, vb = map(float, params[:3])
    except Exception:
        return np.asarray(pyr_obs, dtype=float), np.full_like(pyr_obs, np.nan, dtype=float)
    if not np.all(np.isfinite([kpl, kve, vb])):
        return np.asarray(pyr_obs, dtype=float), np.full_like(pyr_obs, np.nan, dtype=float)

    # For NN parameters, estimate only gamma-AIF nuisance parameters to produce a
    # diagnostic forward curve. This preserves the NN kinetic estimates.
    try:
        fitted = fit_gamma_aif_given_fixed_kinetics(
            time_points=time_points,
            S_pyr_obs=pyr_obs,
            S_lac_obs=lac_obs,
            TR=cfg["SCAN_TR"],
            flips_pyr_deg=cfg["PYR_FA_SCHEDULE"],
            flips_lac_deg=cfg["LAC_FA_SCHEDULE"],
            kpl=kpl,
            kve=kve,
            vb=vb,
            R1p=1 / 30,
            R1l=1 / 25,
            sigma_pyr=sigma_pyr if sigma_pyr is not None else None,
            sigma_lac=sigma_lac if sigma_lac is not None else None,
        )
        return fitted["S_pyr_fit"], fitted["S_lac_fit"]
    except Exception:
        return np.asarray(pyr_obs, dtype=float), np.full_like(pyr_obs, np.nan, dtype=float)


def plot_example_timecourses(
    X: np.ndarray,
    y_true: np.ndarray,
    y_pred_nn: np.ndarray,
    y_pred_nlls: np.ndarray,
    nlls_results: list,
    noise_df: pd.DataFrame,
    cfg: Dict[str, float],
    generator,
    aif_key: str,
    time_points: np.ndarray,
    run_dir: str,
    snr_label: str,
    n_examples: int = 3,
) -> str:
    n_examples = min(int(n_examples), X.shape[0])
    sorted_indices = np.argsort(y_true[:, 0])
    if n_examples == 1:
        example_indices = [sorted_indices[len(sorted_indices) // 2]]
    else:
        q = np.linspace(0, len(sorted_indices) - 1, n_examples).round().astype(int)
        example_indices = [int(sorted_indices[i]) for i in q]

    pyr_max = 1.10 * np.nanmax(X[:, :, 0])
    lac_max = 1.10 * np.nanmax(X[:, :, 1])
    pyr_max = max(pyr_max, 0.1)
    lac_max = max(lac_max, 0.1)

    fig, axes = plt.subplots(n_examples, 2, figsize=(14, 4 * n_examples), squeeze=False)
    for row, sample_idx in enumerate(example_indices):
        pyr_obs = X[sample_idx, :, 0]
        lac_obs = X[sample_idx, :, 1]

        kpl_true, kve_true, vb_true = y_true[sample_idx, :3]
        kpl_nn, kve_nn, vb_nn = y_pred_nn[sample_idx, :3]
        kpl_tr, kve_tr, vb_tr = y_pred_nlls[sample_idx, :3]
        
        sigma_j = float(noise_df.loc[sample_idx, "sigma_equal_rms"])


        pyr_nn, lac_nn = fitted_curves_for_plot(
            aif_key, generator, time_points, pyr_obs, lac_obs, y_pred_nn[sample_idx], cfg, nlls_res=None, sigma_pyr=sigma_j, sigma_lac=sigma_j,
        )
        pyr_tr, lac_tr = fitted_curves_for_plot(
            aif_key, generator, time_points, pyr_obs, lac_obs, y_pred_nlls[sample_idx], cfg, nlls_res=nlls_results[sample_idx]
        )

        param_text = (
            f"NN:    $k_{{PL}}$={kpl_nn:.3f}, $k_{{VE}}$={kve_nn:.3f}, $v_B$={vb_nn:.3f}\n"
            f"NLLS: $k_{{PL}}$={kpl_tr:.3f}, $k_{{VE}}$={kve_tr:.3f}, $v_B$={vb_tr:.3f}"
        )

        ax = axes[row, 0]
        ax.plot(time_points, pyr_obs, "ko", label="Observed", markersize=5, alpha=0.8, zorder=3)
        ax.plot(time_points, pyr_nn, "b-", label="NN fit", linewidth=2.0, zorder=2)
        ax.plot(time_points, pyr_tr, "r--", label="NLLS fit", linewidth=2.0, zorder=1)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Signal (normalized intensity)")
        # ax.set_title(
        #     f"Pyruvate (SNR={noise_df.loc[sample_idx, 'snr_pyr']:.1f})\n"
        #     f"True: $k_{{PL}}$={kpl_true:.3f}, $k_{{VE}}$={kve_true:.3f}, $v_B$={vb_true:.3f}",
        #     fontsize=10,
        # )
        ax.set_title(
            f"Pyruvate: peak={noise_df.loc[sample_idx, 'clean_peak_pyr']:.3f}, "
            f"σ={noise_df.loc[sample_idx, 'sigma_equal_rms']:.4f}, "
            f"SNR={noise_df.loc[sample_idx, 'snr_pyr']:.1f}\n"
            f"True: $k_{{PL}}$={kpl_true:.3f}, $k_{{VE}}$={kve_true:.3f}, $v_B$={vb_true:.3f}",
            fontsize=10,
        )
        ax.set_ylim(0, pyr_max)
        ax.grid(True, alpha=0.3)
        ax.legend(loc="upper left", fontsize=8, framealpha=0.9)
        ax.text(
            0.98,
            0.97,
            param_text,
            transform=ax.transAxes,
            fontsize=8,
            va="top",
            ha="right",
            bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.3),
        )

        ax = axes[row, 1]
        ax.plot(time_points, lac_obs, "ko", label="Observed", markersize=5, alpha=0.8, zorder=3)
        ax.plot(time_points, lac_nn, "b-", label="NN fit", linewidth=2.0, zorder=2)
        ax.plot(time_points, lac_tr, "r--", label="NLLS fit", linewidth=2.0, zorder=1)
        ax.set_xlabel("Time (s)")
        ax.set_ylabel("Signal (normalized intensity)")
        # ax.set_title(
        #     f"Lactate (SNR={noise_df.loc[sample_idx, 'snr_lac']:.1f})\n"
        #     f"True: $k_{{PL}}$={kpl_true:.3f}, $k_{{VE}}$={kve_true:.3f}, $v_B$={vb_true:.3f}",
        #     fontsize=10,
        # )
        ax.set_title(
            f"Lactate: peak={noise_df.loc[sample_idx, 'clean_peak_lac']:.3f}, "
            f"σ={noise_df.loc[sample_idx, 'sigma_equal_rms']:.4f}, "
            f"SNR={noise_df.loc[sample_idx, 'snr_lac']:.1f}\n"
            f"True: $k_{{PL}}$={kpl_true:.3f}, $k_{{VE}}$={kve_true:.3f}, $v_B$={vb_true:.3f}",
            fontsize=10,
        )
        ax.set_ylim(0, lac_max)
        ax.grid(True, alpha=0.3)
        ax.legend(loc="upper left", fontsize=8, framealpha=0.9)
        ax.text(
            0.98,
            0.97,
            param_text,
            transform=ax.transAxes,
            fontsize=8,
            va="top",
            ha="right",
            bbox=dict(boxstyle="round", facecolor="wheat", alpha=0.3),
        )

    fig.tight_layout()
    out = os.path.join(run_dir, f"Example_Timecourses_{snr_label}.png")
    fig.savefig(out, dpi=300, bbox_inches="tight")
    plt.close(fig)
    return out


def main() -> None:
    args = parse_args()

    weights_path = os.path.join(args.output_dir, args.weights_dir, "trained_hybrid_positive.pth")
    training_data_info_path = os.path.join(args.output_dir, args.weights_dir, "training_report.md")
    if not os.path.exists(weights_path):
        raise FileNotFoundError(f"Model weights file not found: {weights_path}")
    if not os.path.exists(training_data_info_path):
        raise FileNotFoundError(f"Training report not found: {training_data_info_path}")

    cfg = load_training_config(training_data_info_path)
    cfg["SNR_MIN"] = float(args.snr_min if args.snr_min is not None else cfg["SNR_MIN"])
    cfg["SNR_MAX"] = float(args.snr_max if args.snr_max is not None else cfg["SNR_MAX"])

    n_timepoints = int(cfg["NUM_TIMEPOINTS"])
    time_points = np.arange(0, n_timepoints * float(cfg["SCAN_TR"]), float(cfg["SCAN_TR"]))
    generator, aif_key = build_generator(cfg, time_points)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    run_dir = os.path.join(args.output_dir, args.weights_dir, f"simulatedData_equalNoise_gammaAIF_{timestamp}")
    os.makedirs(run_dir, exist_ok=True)

    # 1. Generate clean curves, then add equal-rms noise explicitly.
    X_clean, y, met_pools, _ = generate_clean_dataset(generator, n_samples=args.n_samples)
    rng = np.random.default_rng(args.noise_seed)
    X, noise_df = add_equal_rms_noise(
        X_clean=X_clean,
        rng=rng,
        target_pyr_snr_range=(cfg["SNR_MIN"], cfg["SNR_MAX"]),
        fixed_pyr_snr=args.fixed_pyr_snr,
        clip_negative=args.clip_negative_noisy_signal,
    )
    noise_df.to_csv(os.path.join(run_dir, "per_sample_equal_rms_noise_and_snr.csv"), index=False)

    snr_pyr_report = float(noise_df["snr_pyr"].mean())
    snr_lac_report = float(noise_df["snr_lac"].mean())
    snr_label = f"SNR_Pyr_{snr_pyr_report:.1f}_SNR_Lac_{snr_lac_report:.1f}".replace(".", "p")

    # 2. Prepare network inputs exactly as in the training/inference pipeline.
    Xn_test, Xr_test, X_norm, X_raw, clin_meta, alpha, P_clin = prepare_inputs_for_model(
        X, cfg=cfg, P_train=cfg["P_TRAIN"]
    )
    Xr_test_tensor = torch.tensor(Xr_test, dtype=torch.float32)
    Xn_test_tensor = torch.tensor(Xn_test, dtype=torch.float32)
    y_true = np.asarray(y, dtype=float)

    # 3. Load model and infer.
    model = HybridMultiHead(
        input_dim_raw=n_timepoints * 2,
        input_dim_norm=n_timepoints * 2,
        vb_range=(cfg["VB_MIN"], cfg["VB_MAX"]),
        kpl_range=(cfg["KPL_MIN"], cfg["KPL_MAX"]),
        kve_range=(cfg["KVE_MIN"], cfg["KVE_MAX"]),
    )
    model.load_state_dict(torch.load(weights_path, map_location=torch.device("cpu")))
    model.eval()
    with torch.no_grad():
        y_pred_nn = model(Xn_test_tensor, Xr_test_tensor).cpu().numpy()

    # 4. NLLS comparison, using same noisy data and optionally same known sigma for both channels.
    print("Using gamma-AIF NLLS fitting...")
    y_pred_nlls, nlls_results, nlls_failures, nlls_elapsed = run_nlls_fits(
        X=X,
        y_true=y_true,
        noise_df=noise_df,
        cfg=cfg,
        time_points=time_points,
        weighted=args.use_weighted_nlls,
        aif_key=aif_key,
    )
    print(f"NLLS fitting time: {nlls_elapsed:.2f} seconds")
    print(f"NLLS failed or non-converged fits: {nlls_failures} / {X.shape[0]}")

    # 5. Save agreement CSVs and figures.
    nn_base = f"TrueVPred_{snr_label}_NeuralNetwork"
    nlls_base = f"TrueVPred_{snr_label}_NLLS"
    nn_csv = save_true_vs_pred_csv_and_quickplot(y_true, y_pred_nn, run_dir, nn_base)
    nlls_csv = save_true_vs_pred_csv_and_quickplot(y_true, y_pred_nlls, run_dir, nlls_base)

    plot_prediction_scatter(
        y_true,
        y_pred_nn,
        saveName=os.path.join(run_dir, f"NeuralNetwork_{snr_label}"),
    )
    plot_prediction_scatter(
        y_true,
        y_pred_nlls,
        saveName=os.path.join(run_dir, f"GammaAIF_NLLSFitOfGeneratorData_{snr_label}"),
    )

    agreement_script = os.path.join(os.path.dirname(os.path.abspath(__file__)), "plot_param_agreement.py")
    if not os.path.exists(agreement_script):
        agreement_script = "plot_param_agreement.py"
    cmd = [
        sys.executable,
        agreement_script,
        "--csv_nlls",
        nlls_csv,
        "--csv_nn",
        nn_csv,
        "--out",
        os.path.join(run_dir, f"TrueVPred_{snr_label}_Param_Agreement.png"),
        "--bootstrap",
        str(args.bootstrap),
    ]
    print("Running:", " ".join(cmd))
    subprocess.run(cmd, check=True)

    timecourse_path = plot_example_timecourses(
        X=X,
        y_true=y_true,
        y_pred_nn=y_pred_nn,
        y_pred_nlls=y_pred_nlls,
        nlls_results=nlls_results,
        noise_df=noise_df,
        cfg=cfg,
        generator=generator,
        aif_key=aif_key,
        time_points=time_points,
        run_dir=run_dir,
        snr_label=snr_label,
        n_examples=args.n_examples,
    )

    # 6. Summaries for manuscript/reporting.
    r2_nn = finite_r2(y_true, y_pred_nn)
    r2_nlls = finite_r2(y_true, y_pred_nlls)
    r2_nn_std = bootstrap_r2_std(y_true, y_pred_nn, args.bootstrap, rng)
    r2_nlls_std = bootstrap_r2_std(y_true, y_pred_nlls, args.bootstrap, rng)

    summary_df = pd.DataFrame(
        {
            "SNR_Pyruvate_mean": [snr_pyr_report],
            "SNR_Lactate_mean": [snr_lac_report],
            "SNR_Pyruvate_median": [float(noise_df["snr_pyr"].median())],
            "SNR_Lactate_median": [float(noise_df["snr_lac"].median())],
            "sigma_equal_rms_mean": [float(noise_df["sigma_equal_rms"].mean())],
            "R2_NN_kPL": [r2_nn[0]],
            "R2_NN_kPL_std": [r2_nn_std[0]],
            "R2_NN_kVE": [r2_nn[1]],
            "R2_NN_kVE_std": [r2_nn_std[1]],
            "R2_NN_vB": [r2_nn[2]],
            "R2_NN_vB_std": [r2_nn_std[2]],
            "R2_NLLS_kPL": [r2_nlls[0]],
            "R2_NLLS_kPL_std": [r2_nlls_std[0]],
            "R2_NLLS_kVE": [r2_nlls[1]],
            "R2_NLLS_kVE_std": [r2_nlls_std[1]],
            "R2_NLLS_vB": [r2_nlls[2]],
            "R2_NLLS_vB_std": [r2_nlls_std[2]],
            "n_samples": [X.shape[0]],
            "nlls_failures": [nlls_failures],
            "weighted_nlls": [bool(args.use_weighted_nlls)],
            "alpha_input_alignment": [alpha],
            "P_clin": [P_clin],
            "P_train": [cfg["P_TRAIN"]],
        }
    )
    summary_xlsx = os.path.join(run_dir, f"R2_SNR_Summary_{timestamp}.xlsx")
    with pd.ExcelWriter(summary_xlsx) as writer:
        summary_df.to_excel(writer, sheet_name="summary", index=False)
        noise_df.to_excel(writer, sheet_name="per_sample_noise", index=False)

    with open(os.path.join(run_dir, "summary_report.md"), "w", encoding="utf-8") as f:
        f.write("# HP-13C equal-rms noise simulation summary\n\n")
        f.write(f"Date: {datetime.now():%Y-%m-%d %H:%M:%S}\n\n")
        f.write(f"Samples: {X.shape[0]}\n\n")
        f.write("## Noise/SNR definition\n")
        f.write(
            "For each simulated voxel, the same Gaussian rms noise amplitude sigma was added "
            "independently to pyruvate and lactate. SNR was then computed from clean peak signal "
            "divided by that same sigma. Thus pyruvate and lactate SNR differ only because their "
            "signal peaks differ, not because different noise amplitudes were used.\n\n"
        )
        f.write(
            "NLLS used the gamma-variate vascular-input model, fitting AIF nuisance parameters "
            "jointly with kPL, kVE, and vB. NN forward curves in the time-course figure were "
            "generated only for visualization by fitting the gamma-AIF nuisance parameters with "
            "the NN kinetic estimates held fixed.\n\n"
        )
        f.write(f"Mean pyruvate/lactate SNR: {snr_pyr_report:.2f}/{snr_lac_report:.2f}\n")
        f.write(
            f"Median pyruvate/lactate SNR: {noise_df['snr_pyr'].median():.2f}/"
            f"{noise_df['snr_lac'].median():.2f}\n\n"
        )
        f.write("## R2 values\n")
        for i, name in enumerate(PARAMETER_NAMES):
            f.write(
                f"- {name}: NN R2={r2_nn[i]:.3f} ± {r2_nn_std[i]:.3f}; "
                f"NLLS R2={r2_nlls[i]:.3f} ± {r2_nlls_std[i]:.3f}\n"
            )
        f.write("\n## Output files\n")
        f.write(f"- NN CSV: {os.path.basename(nn_csv)}\n")
        f.write(f"- NLLS CSV: {os.path.basename(nlls_csv)}\n")
        f.write(f"- Example timecourses: {os.path.basename(timecourse_path)}\n")
        f.write(f"- Summary workbook: {os.path.basename(summary_xlsx)}\n")

    print("\n" + "=" * 80)
    print("EQUAL-RMS NOISE SIMULATION COMPLETE")
    print("=" * 80)
    print(f"Output directory: {run_dir}")
    print(f"Mean SNR Pyr/Lac: {snr_pyr_report:.2f}/{snr_lac_report:.2f}")
    print(f"Example timecourses: {timecourse_path}")
    print(f"Summary workbook: {summary_xlsx}")
    print("=" * 80)


if __name__ == "__main__":
    main()
